[tool.poetry]
name = "vsc-colors"
version = "0.1.0"
description = ""
authors = ["JoseÌ Duarte <duarte.gmj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
